### Pandas : 

- 파이썬에서 데이터 분석과 처리를 쉽게 할 수있게 도와주는 것 

- Numpy를 기반으로 만들어졌지만 좀 더 복잡한 데이터 분석에 특화

- Numpy는 같은 데이터 타입의 배열만 처리가능/ Pandas는 데이터 타입이 다양하게 섞여있을때도 처리가능

- series(1차원),DataFrame(2차원,시리즈가 모이면 데이터프레임) 등의 자료구를 활용한 데이터분석 기능을 제공해주는 라이브러리 

#### Pandas의 목적 : 

- 서로 다른 유형의 데이터를 공통된 포맷으로 정리

- 행과 열로 이루어진 2차원 데이터 프레임을 처리 할 수있는 함수제공 목적

- 실무 사용 형태 : 데이터 프레임



#### 자료구조 : 시리즈

- 데이터가 순차적으로 나열된 1차원 배열 형태

- 인덱스와 데이터값이 일대일로 대응

- 딕셔너리와 비슷한 구조 {key(index):value}

In [2]:
# <Series를 활용한 데이터 생성>

#1)pandas,numpy 불러오기 :

import pandas as pd

import numpy as np 

 2)데이터를 생성하는 가장 기본적인 방법 : Series()

 시리즈 형식의 데이터를 생성하는 방법 :

 s = pd.Serie(seq_data) 

 seq_data로는 리스트와 튜플 타입의 데이터를 모두 사용할수있지만 주로 리스트데이터를 이용한다.  

In [4]:
#data로만 생성하기 (index는 명시하지 않으면 0부터 자동생성된다)

blank_s = pd.Series()

<ipython-input-4-f5c0f12a90fe>:3: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  blank_s = pd.Series()


In [5]:
s0 = pd.Series(3)
s0

0    3
dtype: int64

In [6]:
s0[0]  # 0번 인덱스의 값 출력

3

In [7]:
# 2개 이상의 원소값을 갖는 시리즈 생성 시 - 리스트,튜플,딕셔너리 등으로 활용
s1 = pd.Series([1,2,30])
s1

0     1
1     2
2    30
dtype: int64

In [8]:
# 서로 다른 데이터 타입의 원소를 갖는 리스트를 이용 - 시리즈의 특징 
s1_1 = pd.Series([1,2.0,3.5,"힘"]) #dtype: object - 숫자와 문자가 혼용되면 문자형태로 시리즈를 만든다 
s1_1

0      1
1    2.0
2    3.5
3      힘
dtype: object

In [9]:
s1_1 = pd.Series([1,2.0,3.5,5]) #dtype: float64
s1_1

0    1.0
1    2.0
2    3.5
3    5.0
dtype: float64

- 범위를 시리즈의 Value 생성하는데 사용하기 - range() / np.arange() 활용

In [10]:
s=pd.Series(range(10,14))
s

0    10
1    11
2    12
3    13
dtype: int64

In [11]:
s = pd.Series(np.arange(200))
print(s)

0        0
1        1
2        2
3        3
4        4
      ... 
195    195
196    196
197    197
198    198
199    199
Length: 200, dtype: int32


- 결측값을 포함해서 시리즈 만들기 :
    - 결측값은 NaN : numpy라는 모듈의 nan 속성을 통해서 생성이 가능 ->"np.nan"`

In [12]:
s = pd.Series([1,2,3,np.nan,6,8]) #결측치 NaN은 float(실수형)으로 처리가 된다
s 

0    1.0
1    2.0
2    3.0
3    NaN
4    6.0
5    8.0
dtype: float64

- 인덱스를 명시해서 시리즈 만들기
- 숫자 인덱스 지정/ 문자 익섹스 지정
- 변수 = pd.Series([값1,값2,...],index=[인덱스1,인덱스2,인덱스3,...])

In [13]:
# 인덱스 명시해서 시리즈 생성
s = pd.Series([10,20,30], index = [1,2,3])
s

1    10
2    20
3    30
dtype: int64

In [14]:
s.index  #인덱스만 출력

Int64Index([1, 2, 3], dtype='int64')

In [15]:
# 인덱스 명시해서 시리즈 생성(문자 인덱스로 만들기)
s = pd.Series([10,20,30], index=["홍길동","이몽룡","성춘향"])
s

홍길동    10
이몽룡    20
성춘향    30
dtype: int64

 - 인덱스 활용:
    - 시리즈는 index는 index속성으로 접근

In [17]:
# 시리즈명. index
s.index

Index(['홍길동', '이몽룡', '성춘향'], dtype='object')

In [18]:
s

홍길동    10
이몽룡    20
성춘향    30
dtype: int64

In [19]:
s.index.name="이름"
s

이름
홍길동    10
이몽룡    20
성춘향    30
dtype: int64

In [20]:
s= pd.Series([9904312,3448737,289045,2466052],
index=["서울","부산","인천","대구"]) #dtype='object' datatype = '문자열객체'
s.index

Index(['서울', '부산', '인천', '대구'], dtype='object')

In [21]:
s.index.name="도시"
s

도시
서울    9904312
부산    3448737
인천     289045
대구    2466052
dtype: int64

In [22]:
# 시리즈의 실제 값 추출 -> 시리즈.values 속성 사용
s.values 

array([9904312, 3448737,  289045, 2466052], dtype=int64)

In [23]:
s.name = "인구"
s

도시
서울    9904312
부산    3448737
인천     289045
대구    2466052
Name: 인구, dtype: int64

딕셔너리로 시리즈 만들기
- Series({key:value,key1:value1....})
- 인덱스 -> key
- 값 -> value
- key가 인덱스로 처리 되므로 명시적으로 인덱스를 설정하게 된다

In [24]:
scores = {'홍길동':96,"이몽룡":100,"성춘향":88}
s = pd.Series(scores)
s


홍길동     96
이몽룡    100
성춘향     88
dtype: int64

In [25]:
city ={"서울":9631482,"부산":3393191,"인천":2632035,"대전":1490158}
s = pd.Series(city)
s


서울    9631482
부산    3393191
인천    2632035
대전    1490158
dtype: int64

In [ ]:
- 딕셔너리의 원소는 순서를 갖지 않는다.
- 딕셔너리로 생성된 시리즈의 원소도 순서가 보장되지 않는다.
- 만약 순서를 보장하고 싶으면 인덱스를 리스트로 지정해야 한다.

In [28]:
s2 = pd.Series(city,index=["부산","인천","서울","대전"])
s2

부산    3393191
인천    2632035
서울    9631482
대전    1490158
dtype: int64

인덱싱 :
- 데이터에서 특정한 데이터를 추출하는 것

시리즈의 인덱싱 종류
1. 정수형 위치 인덱스(integer position)

2. 인덱스 이름(index name) 또는 인덱스 라벨(index label)
    -  인덱스 별도 지정하지 않으면 0부터 시작하는 정수형 인덱스가 지정됨
    
- 원소 접근
    -   정수형 인덱스 : 숫자 s[0]
    -    문자형 인덱스 : 숫자 s["인천"]


In [29]:
print(s.index)
s

Index(['서울', '부산', '인천', '대전'], dtype='object')


서울    9631482
부산    3393191
인천    2632035
대전    1490158
dtype: int64

In [30]:
# 위치 인덱스
s[0]

9631482

In [31]:
# 라벨 인덱스
s["서울"]

9631482

In [32]:
### 확인 예제 
s_1 = pd.Series([1,2,3],index=[1,2,3])
s_1

1    1
2    2
3    3
dtype: int64

In [34]:
s_1.index


Int64Index([1, 2, 3], dtype='int64')

In [41]:
# s_1[0]  #인덱스 타입이 정수이면 위치 인덱스는 사용이 불가능 !!


In [43]:
# 한줄에 위치 인덱스, 문자 인덱스를 동시에 접근 
print(s)
s[3],s["대전"] # ,콤마가 들어가면서 튜플이 생성 

서울    9631482
부산    3393191
인천    2632035
대전    1490158
dtype: int64


(1490158, 1490158)

리스트 이용 인덱싱
- 자료의 순서를 바꿔 반환하거나, 특정 자료 여러개를 선택할 때 사용 
- 시리즈명 [[인덱스1,인덱스2,...]]

In [45]:
print(s)
s[[0,3,2,1]]

서울    9631482
부산    3393191
인천    2632035
대전    1490158
dtype: int64


서울    9631482
대전    1490158
인천    2632035
부산    3393191
dtype: int64

In [46]:
s[["서울","인천"]] # 특정자료만 선택

서울    9631482
인천    2632035
dtype: int64

시리즈 슬라이싱을 이용한 인덱싱
- 정수형 위치 인덱스를 사용한 슬라이싱
-  시리즈[start:stop+1]
- 문자(라벨)인덱스 이용 슬라이싱
-  시리즈['시작라벨':'끝라벨'] : 표시된 라벨 범위 모두 추출
    

In [48]:
s

서울    9631482
부산    3393191
인천    2632035
대전    1490158
dtype: int64

In [49]:
s[1:3]

부산    3393191
인천    2632035
dtype: int64

In [51]:
s["부산":"대전"]

부산    3393191
인천    2632035
대전    1490158
dtype: int64

In [52]:
s_test = pd.Series([1,2,3,4],index=[1,3,5,7])
s_test

1    1
3    2
5    3
7    4
dtype: int64

In [55]:
s_test[1:10] # 출력 할 수잇는 값까지만 출력하고 끝 

1    1
3    2
5    3
7    4
dtype: int64

In [56]:
### 문자 인덱스인 경우에는 .(다트)를 이용해서 접근 할 수 있음
s

서울    9631482
부산    3393191
인천    2632035
대전    1490158
dtype: int64

In [59]:
print(s.서울)
print(s.인천) 
# 문자인덱스에 큰따옴표 붙이면 안됨

9631482
2632035


In [60]:
s_test

1    1
3    2
5    3
7    4
dtype: int64

인덱싱을 통한 데이터 업데이트
- 시리즈명[인덱스] = 데이터값

In [61]:
s

서울    9631482
부산    3393191
인천    2632035
대전    1490158
dtype: int64

In [62]:
s["서울"]=10000000
s

서울    10000000
부산     3393191
인천     2632035
대전     1490158
dtype: int64

### 인덱스 재사용 가능

In [64]:
print(s.index)
s1 = pd.Series(np.arange(4),s.index)
s1

Index(['서울', '부산', '인천', '대전'], dtype='object')


서울    0
부산    1
인천    2
대전    3
dtype: int32

### 벡터화 연산 
- Numpy 배열처럼 Pandas의 시리즈도 벡터화 연산 가능
- 벡터화 연산이란 집합적 자료형의 원소 각각을 독립적으로 계산을 진행하는 방법(단, 연산은 시리즈의 값에만 적용, 인덱스값은 변경불가)


In [66]:
pd.Series([1,2,3])+4

0    5
1    6
2    7
dtype: int64

In [67]:
s/1000000

서울    10.000000
부산     3.393191
인천     2.632035
대전     1.490158
dtype: float64

In [68]:
s * 47

서울    470000000
부산    159479977
인천    123705645
대전     70037426
dtype: int64

In [69]:
# 백터화 인덱싱 - 인덱싱에 조건식을 활용 할 수 있다 
# 시리즈 s의 원소 값 중 2500000(250e4) 보다 크고 5000000(500e4) 보다 작은 원소를 추출 
# 시리즈명[조건식] - 각 원소의 값 모두를 각각 조건식으로 확인해서 결과가 true인 원소만 추출 

s[(s>250e4) & (s<500e4)]


부산    3393191
인천    2632035
dtype: int64

#### **Boolean selection**
  - boolean Series가 [ ]와 함께 사용되면 True 값에 해당하는 값만 새로 반환되는 Series객체에 포함됨
  - 다중조건의 경우, &(and), |(or)를 사용하여 연결 가능

In [71]:
s0 = pd.Series(np.arange(10), np.arange(10)+1)
s0


1     0
2     1
3     2
4     3
5     4
6     5
7     6
8     7
9     8
10    9
dtype: int32

In [72]:
s0 > 5

1     False
2     False
3     False
4     False
5     False
6     False
7      True
8      True
9      True
10     True
dtype: bool

In [73]:
s0[s0>5]

7     6
8     7
9     8
10    9
dtype: int32

In [74]:
s0 % 2 ==0
s0[s0 % 2 ==0]

1    0
3    2
5    4
7    6
9    8
dtype: int32

In [75]:
s0.index > 5 #s0의 인덱스 값을 추출해서 벡터화 연산을 진행한것 

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [78]:
s0[s0.index > 5]

6     5
7     6
8     7
9     8
10    9
dtype: int32

In [79]:
s0[s0.index > 10]

Series([], dtype: int32)

In [80]:
s0[s0.index > 9]

10    9
dtype: int32

In [81]:
(s0 >= 7).sum()  # 각 원소에 대해여 조건식의 결과값이 True인 원소의 개수 

3

In [82]:
print(s0[s0>=7]) 
s0[s0>=7].sum() # 각 원소에 대해 대입한 조건식의 결과값이 True인 원소들의 합  

8     7
9     8
10    9
dtype: int32


24

In [87]:
num_s1 = pd.Series([1,2,3,4],index=['a','b','c','d'])
num_s2 = pd.Series([5,6,7,8],index=['b','c','d','a'])
print(num_s1)
num_s2

a    1
b    2
c    3
d    4
dtype: int64


b    5
c    6
d    7
a    8
dtype: int64

In [86]:
num_s1 + num_s2 # 시리즈 간의 연산은 같은 인덱스를 찾아 진행 

a     9
b     7
c     9
d    11
dtype: int64

In [88]:
num_s3 = pd.Series([1,2,3,4],index=['e','b','f','g'])
num_s4 = pd.Series([5,6,7,8],index=['b','c','d','a'])
print(num_s3)
num_s4

e    1
b    2
f    3
g    4
dtype: int64


b    5
c    6
d    7
a    8
dtype: int64

In [89]:
num_s3 + num_s4 #b를 제외한 나머지 인덱스는 연산처리가 불가능해서 NaN값으로 처리

a    NaN
b    7.0
c    NaN
d    NaN
e    NaN
f    NaN
g    NaN
dtype: float64

In [90]:
num_s4.values - num_s3.values
# values속성을 사용하면 시리즈의 형태가 사라지므로 동일한 위치 원소들끼리 연산 
# 시리즈의 values는 array 형태를 반환 

array([4, 4, 4, 4], dtype=int64)

##### 딕셔너리 와 시리즈의 관계
- 시리즈 객체는 라벨(문자)에 의해 인덱싱이 가능
- 실질적으로는 라벨을 key로 가지는 딕셔너리 형과 같다고 볼 수 있음
- 딕셔너리에서 제공하는 대부분의 연산자 사용 가능
    - in 연산자 : T/F
    - for 루프를 통해 각 원소의 key와 value에 접근 할수 있다.

In [93]:
s

서울    10000000
부산     3393191
인천     2632035
대전     1490158
dtype: int64

In [94]:
"서울" in s

True

In [95]:
"대구" not in s


True

In [96]:
# 딕셔너리의 items()함수 시리즈에서도 사용 가능
s.items() 
list(s.items())

[('서울', 10000000), ('부산', 3393191), ('인천', 2632035), ('대전', 1490158)]

In [97]:
# 반복문을 활용해서 시리즈 각 원소 출력 코드
for k,v in s.items() :
    print('%s = %d' %(k,v))

서울 = 10000000
부산 = 3393191
인천 = 2632035
대전 = 1490158


### 시리즈 데이터의 갱신 / 추가 / 삭제 
- 인덱싱을 이용하면 딕셔너리처럼 갱신 추가

In [98]:
s

서울    10000000
부산     3393191
인천     2632035
대전     1490158
dtype: int64

In [99]:
s["부산"] = 8630000
s

서울    10000000
부산     8630000
인천     2632035
대전     1490158
dtype: int64

In [102]:
s["대구"] = 1875000
s


서울    10000000
부산     8630000
인천     2632035
대구     1875000
dtype: int64

In [101]:
# 시리즈의 데이터를 삭제 : del 명령 사용 
del s["대전"]
s

서울    10000000
부산     8630000
인천     2632035
대구     1875000
dtype: int64

### Series 함수
#### **Series size, shape, unique, count, value_counts 함수**
 - size 속성: 개수 반환
 - shape  속성: 튜플형태로 shape반환
 - unique 함수: 유일한 값만 ndarray로 반환
 - count 함수: NaN을 제외한 개수를 반환
 - mean 함수: NaN을 제외한 평균 
 - value_counts 함수: NaN을 제외하고 각 값들의 빈도를 반환

In [103]:
s1 = pd.Series([1, 1, 2, 1, 2, 2, 2, 1, 1, 3, 3, 4, 5, 5, 7, np.NaN])
s1


0     1.0
1     1.0
2     2.0
3     1.0
4     2.0
5     2.0
6     2.0
7     1.0
8     1.0
9     3.0
10    3.0
11    4.0
12    5.0
13    5.0
14    7.0
15    NaN
dtype: float64

In [104]:
len(s1) #NaN값 포함

16

In [105]:
s1.size#NaN값 포함한 개수

16

In [106]:
s1.shape #차원을 표현하기 때문에 튜플 형태로 출력 (16행 1열(,))

(16,)

In [107]:
s1.unique() #중복값을 제거한 원소 값 출력

array([ 1.,  2.,  3.,  4.,  5.,  7., nan])

In [108]:
s1.count() # NaN 값을 제거한 원소의 개수 

15

In [111]:
a = np.array([2,2,2,2,2,np.NaN]) #결측치 포함 
b = pd.Series(a)
print(a.mean()) # np의 array를 평균계산 - nan이 포함되면 계산이 불가능해서 nan이 반환됨 
b.mean()# 기본 nan값을 제외시키고 계산하도록 설정 됨 

nan


2.0

In [112]:
s1

0     1.0
1     1.0
2     2.0
3     1.0
4     2.0
5     2.0
6     2.0
7     1.0
8     1.0
9     3.0
10    3.0
11    4.0
12    5.0
13    5.0
14    7.0
15    NaN
dtype: float64

In [114]:
s1.mean()

2.6666666666666665

In [116]:
s1.value_counts()# 각 원소들을 같은 값끼리 그룹을 만들고 그 그룹의 개수를 세서 반환 

1.0    5
2.0    4
3.0    2
5.0    2
7.0    1
4.0    1
dtype: int64

## date_range함수
- 시리즈의 인덱스에 날짜 데이터를 사용
- 날짜표시 : "년-월-일"

In [117]:
index_date = ['2018-10-07','2018-10-08','2018-10-09','2018-10-10']
s4 = pd.Series([200,195,np.nan, 205], index=index_date)
s4

2018-10-07    200.0
2018-10-08    195.0
2018-10-09      NaN
2018-10-10    205.0
dtype: float64

In [118]:
type(s4.index[0]) # 문자열 형태 

str

- 판다스 패키지의 date_range 함수 (날짜생성)
    - pd.date_range(start=None, end=None, periods=None, freq='D')
    - start : 시작날짜/ end= 끝날짜 / periods = 날짜 생성기간/ frep = 날짜 생성 주기
    - start는 필수 옵션/end나 periods는 둘 중 하나가 있어야 함/ freq는 기본 Day로 설정

In [121]:
pd.date_range(start="2018-10-01", end="2018-10-20") #dtype='datetime64[ns] 데이트 타임 형태로 생성 

DatetimeIndex(['2018-10-01', '2018-10-02', '2018-10-03', '2018-10-04',
               '2018-10-05', '2018-10-06', '2018-10-07', '2018-10-08',
               '2018-10-09', '2018-10-10', '2018-10-11', '2018-10-12',
               '2018-10-13', '2018-10-14', '2018-10-15', '2018-10-16',
               '2018-10-17', '2018-10-18', '2018-10-19', '2018-10-20'],
              dtype='datetime64[ns]', freq='D')

In [122]:
pd.date_range(start="2018-10-01", end="2018-10-20",freq="d") #freq 기본값 = "d"

DatetimeIndex(['2018-10-01', '2018-10-02', '2018-10-03', '2018-10-04',
               '2018-10-05', '2018-10-06', '2018-10-07', '2018-10-08',
               '2018-10-09', '2018-10-10', '2018-10-11', '2018-10-12',
               '2018-10-13', '2018-10-14', '2018-10-15', '2018-10-16',
               '2018-10-17', '2018-10-18', '2018-10-19', '2018-10-20'],
              dtype='datetime64[ns]', freq='D')

In [123]:
pd.date_range(start="2018-10-01", end="2018-10-20",freq="3d") # 3일씩 증가 

DatetimeIndex(['2018-10-01', '2018-10-04', '2018-10-07', '2018-10-10',
               '2018-10-13', '2018-10-16', '2018-10-19'],
              dtype='datetime64[ns]', freq='3D')

In [124]:
pd.date_range(start="2018-10-01", end="2018-10-20",freq="w") 

DatetimeIndex(['2018-10-07', '2018-10-14'], dtype='datetime64[ns]', freq='W-SUN')

In [125]:
pd.date_range(start="2018-10-07", periods=4, freq="w")

DatetimeIndex(['2018-10-07', '2018-10-14', '2018-10-21', '2018-10-28'], dtype='datetime64[ns]', freq='W-SUN')

In [126]:
pd.date_range(start="2018-10-07", periods=4, freq="m") #월말 

DatetimeIndex(['2018-10-31', '2018-11-30', '2018-12-31', '2019-01-31'], dtype='datetime64[ns]', freq='M')

In [127]:
pd.date_range(start="2018-10-07", periods=4, freq="MS") #월초를 나타낼때는 무조건 대문자(ms가 초의 단위를 표시하고있기 때문)

DatetimeIndex(['2018-11-01', '2018-12-01', '2019-01-01', '2019-02-01'], dtype='datetime64[ns]', freq='MS')

In [128]:
pd.date_range(start="2018-10-07", periods=4, freq="QS") # 분기의 첫째 날짜 생성하기(10월7일을 기준으로 다음 분기부터)

DatetimeIndex(['2019-01-01', '2019-04-01', '2019-07-01', '2019-10-01'], dtype='datetime64[ns]', freq='QS-JAN')

In [129]:
pd.date_range(start="2018-1-1", periods=4, freq="AS") #연도 첫날 기준으로 4개의 연도 첫날짜 생성 

DatetimeIndex(['2018-01-01', '2019-01-01', '2020-01-01', '2021-01-01'], dtype='datetime64[ns]', freq='AS-JAN')

In [130]:
pd.date_range(start="2018-1-20", periods=4, freq="AS") #연 초를 구하기때문에 다음년도 부터 생성 

DatetimeIndex(['2019-01-01', '2020-01-01', '2021-01-01', '2022-01-01'], dtype='datetime64[ns]', freq='AS-JAN')